### ISSUE TITLE
add file encoding set

### ISSUE THREAD

**Issue by leiyu1139** [mefengl/vscode-copy-folder-content#31]
When copying a GBK encoded file/folder, the Chinese is garbled.Is it possible to add the encoding settings？

**Comment by mefengl** [comment]
Thank you for informing me about this issue. It should be resolved at https://github.com/mefengl/vscode-copy-folder-content/commit/f6c7e7763e4f070448ce748217a8ff845cf20072.

The copy should be fine after you update this extension.
