### ISSUE TITLE
Publish `Releases` to subscribe to new changes.

### ISSUE THREAD

**Issue by guillempuche** [mefengl/vscode-copy-folder-content#33]
It's a fantastic plugin!

**Comment by mefengl** [comment]
Okay, if there are updates in the future, a release will also be published

**Comment by mefengl** [comment]
Actually, I do have an updated plan, which is to add more UI-based operations instead of doing it like the current right-click menu, but I haven't decided yet whether to continue updating this plugin or to write a separate electron application :)

**Comment by guillempuche** [comment]
Your plugin is super helpful 💪. You could talk to a Youtube or X creator to promote it.

The one thing I'd improve is to know what files are being stored, then faster clear and copy. Your idea of a UI could help on this.

**Comment by mefengl** [comment]
> You could talk to a Youtube or X creator to promote it.

I am not in a rush to promote it; those who are lucky get to use it first :)

> Your plugin is super helpful 💪. You could talk to a Youtube or X creator to promote it. The one thing I'd improve is to know what files are being stored, then faster clear and copy. Your idea of a UI could help on this.

You make a good point. I'm considering using a file tree for selection, but I'm unsure if vscode can easily support it. Anyway, I plan to work on this in the near future.

**Comment by mefengl** [comment]
Hi @guillempuche, I have some updates. I made a cli tool called `pray` that you can install with `cargo install pray`.

Here's the repo: https://github.com/mefengl/pray

@wenwu35, I'm tagging you since you're one of the contributors :)

**Comment by guillempuche** [comment]
The UI in the terminal looks good. I opened an improvement https://github.com/mefengl/pray/issues/1

What is the vision for Pray? VSCode Copy Folder Content makes it easier to copy content with the mouse.

**Comment by mefengl** [comment]
@guillempuche The main reason was because building the same feature as a vscode extension was too hard. Not sure if I'll add more features to `pray`.
