### ISSUE TITLE
feat: close automatically the success notifications

### ISSUE THREAD

**Issue by guillempuche** [mefengl/vscode-copy-folder-content#34]
The extension shows the success notifications after copying files. It would be handy to autoclose them after 5 seconds, sometimes I have 3 or 4 of those messages.

---

PS: the new menu items "Copy from new", etc, are very handy. Bravo!

**Comment by mefengl** [comment]
‌The implementation has been modified and is now displayed in the status bar at the bottom left corner, try it to see if it resolves the issue you mentioned :)

**Comment by guillempuche** [comment]
Uoooo, fantastic news!

Cursor's extensions take some time to have the latest versions. I'll reopen again the issue if I encounter a problem.

**Comment by guillempuche** [comment]
I'm using Cursor (fork of VSCode). It has the same marketplace.

![imatge](https://github.com/user-attachments/assets/82d289b4-ad8b-4dba-b9da-3c9a9147987f)

I still get the issue. And I don't see the status bar.

Another extension _swmansion.react-native-ide_ has this:
![imatge](https://github.com/user-attachments/assets/377cd1f4-0d3f-4b4a-a8a3-3a9da17abfd4)

**Comment by mefengl** [comment]
<img width="173" alt="image" src="https://github.com/user-attachments/assets/5ec85afd-c9b5-4192-800f-d59e09454b6a">

It's fine on my end, maybe you can try uninstalling and reinstalling to resolve the issue.

**Comment by guillempuche** [comment]
Good, I did it.

What should I see in the status bar?

**Comment by mefengl** [comment]
<img width="368" alt="image" src="https://github.com/user-attachments/assets/0967fc93-5410-4798-8289-e424e2d59c52">

something like this

**Comment by guillempuche** [comment]
I don't see it. I right click on the status bar, also I don't see this extension option to show/hide.

**Comment by mefengl** [comment]
<img width="340" alt="image" src="https://github.com/user-attachments/assets/00f6acad-95ff-4947-8cfd-c26529e0e568">

Right-clicking on the status bar is invisible, and information will only be displayed here after an operation has been performed

**Comment by guillempuche** [comment]
I don't see any new info in the status bar.

Version:
Last released: 2024-09-24, 10:07:44
Last updated: 2024-09-29, 15:00:16

**Comment by mefengl** [comment]
‌‌I'm pretty sure it's because the Cursor doesn't have the latest code dependencies, so let's roll back a little bit. When version `v1.4.7` is released, it should be fine then.

**Comment by guillempuche** [comment]
Cool! Thanks again for this extension.
